const express = require('express')
const mongoose = require('mongoose')
const dotenv = require('dotenv')
dotenv.config()
const cors = require('cors')
const passport = require('./middleware/passport')
const authRoutes = require('./routes/authRoutes')
const metricsRoutes = require('./routes/metricsRoutes')
const logRoutes = require('./routes/logRoutes')
const targetRoutes = require('./routes/targetRoutes')
const collectLogs = require('./workers/logCollector')
require('./workers/metricsWorker')
require('./workers/investigationWorker')
const app = express()
app.use(express.json())
app.use(cors())
app.use(passport.initialize())
mongoose.connect(process.env.MONGO_URI)
  .then(() => {
    collectLogs()
  })
  .catch((err) => {
  })
app.use('/api/auth', authRoutes)
app.use('/api/metrics', metricsRoutes)
app.use('/api/logs', logRoutes)
app.use('/api/target', targetRoutes)
app.listen(process.env.PORT)